
site_name: 'AWS - Cloud Computing | Lister Ogusuku Ribeiro'

theme:
  features:
    - instant
    - navigation.expand
    - tabs: true
    # - toc.integrate
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.code.annotation
    # - content.code.copy
  name: 'material'
  palette:
      primary: 'black'
      accent: 'pink'
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/listerogusuku
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCJGD3ksGrX45TId4EyQKaiQ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lister-ogusuku-ribeiro-6a1052148/

# Copyright
copyright: 'Layout Copyright &copy; 2019 by Prof. Rafael Corsi / rafael.corsi@insper.edu.br | Written material Copyright &copy; 2023 by Lister Ogusuku Ribeiro / listeror@al.insper.edu.br'

# repo
docs_dir: docs-src
site_dir: docs

nav:
  - Home: index.md
  - Vídeos interessantes: interestingvideos.md

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search